# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Dependencies
    init: |
      npm install -g yarn 
      yarn install
      gp sync-done deps
  - name: Start Dev Server
    init: gp sync-await deps
    command: yarn run serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: notify
